### ISSUE TITLE
[ENHANCEMENT]: Dynamic macOS number

### ISSUE THREAD

**Issue by iggy890** [CodeEditApp/codeedit.app#35]
The macOS build number on the homepage should be dynamic changing with every (major) macOS release, probably with an API.

**Comment by bombardier200** [comment]
I'm going to take a look at this, we merged a change that was supposed to do this but it seems to be failing

**Comment by lukepistrol** [comment]
Do you mean the _macOS_ build number or the _CodeEdit_ build number?

The latter is already implemented but it fails for some reason on the production environment.

The first does not need to be dynamic since it will only change in major releases of the app. It is bound to the minimum deployment target of the app - not the latest release of macOS.

**Comment by iggy890** [comment]
> Do you mean the _macOS_ build number or the _CodeEdit_ build number?

The macOS build number, in the github download page it mentions the minimum macOS version
